intersective/app-v2

- src/app/chat/chat-list/chat-list.component.html
- src/app/chat/chat-list/chat-list.component.scss
- src/app/chat/chat-list/chat-list.component.ts
- src/app/chat/chat-room/chat-room.component.html
- src/app/chat/chat-room/chat-room.component.scss
- src/app/chat/chat-room/chat-room.component.spec.ts
- src/app/chat/chat-room/chat-room.component.ts
- src/app/chat/chat-routing.module.ts
- src/app/chat/chat-service/chat.service.spec.ts
- src/app/chat/chat-service/chat.service.ts
- src/app/chat/chat.component.ts
- src/app/chat/chat.module.ts
- src/app/tabs/tabs-routing.module.ts
- src/theme/variables.scss
chat module pages style things are done but there is a one issue in routes. can’t navigate to chat room from chat list. After i fixed routing issue in chat room footer will not show and it will have a back button. For fixing that i will create a new jira story.
> Feature/av2 21/set up chat module

- src/app/activity/activity.component.html
- src/app/activity/activity.service.ts
different icon for different assessment status
> [AV2-68]Change assessment icon based on the status

- scripts/install_dependencies
- template.yml
> rebuild node-sass

- package.json
> Enable ssl for test deployment

- angular.json
- buildspec.yml
- package.json
- scripts/install_dependencies
- src/environments/environment.stage.ts
- src/environments/environment.ts
1. remove the build and install commands to the build specification yml
2. launch the app with a specific environment variables
> add stage environment configurations

- scripts/install_dependencies
- template.yml
remove npm install when install dependencies in the deployment server
> update instance type

- appspec.yml
- buildspec.yml
- scripts/stop_server
- scripts/sync_s3_bucket
- template.yml
1. upgrade instance type to t2.medium
2. upgrade awscli when instance is creating
3. remove port 8000
> move s3 sync to app server scripts

- src/app/fast-feedback/fast-feedback.component.ts
> [AV2-165] fixed null param 

- src/app/assessment/assessment.component.html
- src/app/auth/auth.service.ts
apply latest codes to the test branch
> Develop to Master

- src/app/fast-feedback/fast-feedback.component.html
- faadst feedback pop up title change
> [AV2-185] Fast feedback pop up title change 

- src/index.html
- src/index.prod.html
> [AV2-217] app title update 

- src/app/chat/chat-room/chat-room.component.ts
added mark as seen after got message from pusher.
> [AV2-219] chat pusher loads duplicate messages

- src/app/questions/multiple/multiple.component.html
- src/app/questions/oneof/oneof.component.html
- src/app/questions/team-member-selector/team-member-selector.component.html
- src/app/switcher/switcher-program/switcher-program.component.html
- src/styles.scss
create a new css class.
added that class to question components and to swicher component.
> [AV2-236] fixed white space issue.

- src/app/topic/topic.component.ts
- src/app/topic/topic.service.ts
image alignment issue fixed.
added methods to topic service to add extra style to content.
> [AV2-245] Image mis alignment in topic content

- src/app/assessment/assessment.service.ts
fixed issue submission page not loading after review publish.
> Task/av2 261/ auto saving feature bug fix

- src/app/assessment/assessment.component.scss
- src/app/assessment/assessment.component.ts
- remove 'a moment ago` and added current time.
- fixed issue found overlapping saving label.
> [AV2-274] Auto saved timestamp text always display Last saved a moment ago

- src/app/questions/text/text.component.ts
update time out time to 10 second.
> [AV2-275] auto saved to a text question does not submit the latest changes

- src/app/assessment/assessment.component.ts
- src/app/questions/file/file.component.ts
- src/app/questions/multiple/multiple.component.ts
- src/app/questions/oneof/oneof.component.ts
- src/app/questions/team-member-selector/team-member-selector.component.ts
- src/app/questions/text/text.component.ts
use control.setValue to set answers to controllers in question components.
update assessment component to send empty string if there is no answer.
> [AV2-284] send out the empty question answers

- src/app/assessment/assessment.service.ts
- src/app/questions/multiple/multiple.component.ts
- pass array before push value.
- fix issue assign array to array.
> [AV2-287] cannot modify answers of the checkbox question

- src/app/settings/setting.service.ts
- src/app/settings/settings.component.html
- src/app/settings/settings.component.scss
- src/app/settings/settings.component.ts
- src/app/settings/settings.module.ts
- src/app/shared/filestack/filestack.component.html
- src/app/shared/filestack/filestack.component.scss
- src/app/shared/filestack/filestack.component.ts
added new css and html element for show profile image.
> [AV2-252] Profile pictures on settings page

- src/app/event-detail/event-detail.component.ts
- src/app/event-detail/event-detail.service.ts
- src/app/events/events.component.ts
- src/app/events/events.service.ts
changelogs
- [AV2-292] single booking
> 2019_04_29-us-release

- src/app/shared/components/description/description.component.ts
https://intersective.atlassian.net/browse/AV2-296
> [AV2-296] preview now ready

- src/app/chat/chat-room/chat-room.component.html
fixed issue when receiving message.
fixed profile image alignment issue.
> [AV2-253] Profile picture on chat.

- src/app/app-routing.module.ts
- src/app/project/project.component.html
- src/app/project/project.component.scss
- src/app/project/project.component.ts
[AV2-290] activity scrolling issue
> Release-2019_05_06

- src/app/app-routing.module.ts
- src/app/project/project.component.html
- src/app/project/project.component.scss
- src/app/project/project.component.ts
Changelog
- [AV2-290] Bugfix/scroll issue
> Release_AUS-2019_05_06

- src/app/app-routing.module.ts
- src/app/project/project.component.html
- src/app/project/project.component.scss
- src/app/project/project.component.ts
changelog
- [AV2-290] activity scrolling issue
> Release-US_2019_05_06

- src/app/assessment/assessment.component.html
removed logic to show submitter name only on team assessment.
> [AV2-300] Reviewer page do not display the submitter's name

- src/app/assessment/assessment.component.html
- src/app/assessment/assessment.component.ts
- src/app/assessment/assessment.service.ts
https://intersective.atlassian.net/browse/AV2-293
> [AV2-293] corrected wrong data type conversion

- src/app/activity/activity.component.html
- src/app/activity/activity.component.ts
- src/app/event-detail/event-detail.component.html
- src/app/event-detail/event-detail.component.scss
- src/app/event-detail/event-detail.component.ts
- src/app/shared/components/event-card/event-card.component.html
- src/app/shared/components/event-card/event-card.component.scss
Jira story - https://intersective.atlassian.net/browse/AV2-318
In this story 
- need to show indicate to user expired event in event detail popup, in activity page and in event list page.
- need to add time to event card in activity page.
> [AV2-318] Event booking - expired events indicators

- src/app/auth/auth-login/auth-login.component.ts
jira bug story - https://intersective.atlassian.net/browse/AV2-325
> [AV2-325] Password compromised Login button

- src/environments/environment.dev.ts
- src/environments/environment.ts
dev and local api endpoint changed to sandbox.practera.com
> update dev and local env

- src/app/assessment/assessment.service.ts
- src/app/questions/multiple/multiple.component.html
- src/app/questions/oneof/oneof.component.html
Jira story - https://intersective.atlassian.net/browse/AV2-315
need to fix issue in quiz assessments after submit explanation not rendering HTML content correctly.
> [AV2-315] Answer explanation in quiz not interpreting html

- src/app/shared/components/event-card/event-card.component.html
- src/app/shared/components/event-card/event-card.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-319
need to fix issue when event link to assessment that event not grey out after expired.
> [Av2-319] the event card does not grey out

- hooks/post-build.js
- package.json
- src/app/app.component.ts
- src/app/app.module.ts
- src/app/services/version-check.service.ts
- src/app/shared/request/request.service.ts
https://intersective.atlassian.net/browse/AV2-329
> [AV2-329] Feature/version tracking (direct update to master for testing)

- buildspec.yml
to update docker to run postscript before syncing www folder
[AV2-329] 
https://intersective.atlassian.net/browse/AV2-329
> [AV2-329] Feature/version tracking

- buildspec.yml
- src/app/assessment/assessment.component.ts
jira story - https://intersective.atlassian.net/browse/AV2-302
> Bug/av2 302/displaying assessmet form rather than assessment review

- src/app/assessment/assessment.component.html
- src/app/assessment/assessment.component.scss
- src/app/assessment/assessment.component.ts
- src/app/assessment/assessment.service.ts
Jira FE - https://intersective.atlassian.net/browse/AV2-312
Jira BE - https://intersective.atlassian.net/browse/CORE-3615
in this FE story need to show reviewer name in feedback page. for that submission api need to update.
for review page FE implemented the logic api will update from another story.
> [AV2-312] Review and feedback page should display reviewer name

- src/app/shared/components/contact-number-form/contact-number-form.component.ts
- src/environments/environment.dev.ts
- src/environments/environment.local.ts
- src/environments/environment.prod.ts
- src/environments/environment.stage.ts
- src/environments/environment.trial.ts
- src/environments/environment.ts
- src/environments/environment.us.ts
Jira story - https://intersective.atlassian.net/browse/AV2-317
In this story previous changes working fine but for more code readability added default country model to environment files and use in contact number form from environment file.
> [AV2-317] Default country need to change related to environment.

- src/app/project/project.component.html
- src/app/project/project.component.ts
https://intersective.atlassian.net/browse/AV2-331
> [AV2-331] hotfix/brought back scroll tracking

- src/app/project/project.component.html
- src/app/project/project.component.scss
- src/app/shared/pusher/pusher.service.ts
Jira story - https://intersective.atlassian.net/browse/AV2-337?oldIssueView=true
In this story need to remove milestone text shows to user.
> [AV2-337] Remove 'Milestone' text

- src/app/assessment/assessment.component.html
- src/app/assessment/assessment.component.ts
from https://github.com/intersective/practera-app-v2/commit/8ffffd3ece83c89f49891d2e5130129f6b679fc3
> Fix to mentor cannot submit the review

- package-lock.json
- package.json
- src/app/app.component.ts
- src/app/auth/auth-login/auth-login.component.ts
- src/app/auth/auth.service.ts
- src/app/chat/chat-room/chat-room.component.ts
- src/app/services/shared.service.ts
- src/app/shared/pusher/pusher.module.ts
- src/app/shared/pusher/pusher.service.ts
- src/app/switcher/switcher-program/switcher-program.component.ts
https://intersective.atlassian.net/browse/AV2-340
> [AV2-340] Hotfix/pusher optimisation

- src/app/questions/multiple/multiple.component.html
- src/app/questions/oneof/oneof.component.html
https://intersective.atlassian.net/browse/AV2-339
> AV2-339 incorrect display of quiz answer explanation

- e2e/src/app.e2e-spec.ts
- src/app/achievements/achievements.component.html
- src/app/achievements/achievements.component.scss
- src/app/achievements/achievements.component.ts
- src/app/settings/settings.component.html
- src/app/settings/settings.component.spec.ts
- src/app/switcher/switcher-program/switcher-program.component.html
Jira story - https://intersective.atlassian.net/browse/AV2-351
Replaced 'Select a Program' with 'Select an Experience'
changed in settings page - 'Switch to another experience'
> Task/av2 351/replace select a program with something generic

- src/app/achievements/achievements.component.html
- src/app/achievements/achievements.component.scss
- src/app/achievements/achievements.component.ts
- src/app/services/version-check.service.ts
https://intersective.atlassian.net/secure/RapidBoard.jspa?rapidView=62&projectKey=AV2&modal=detail&selectedIssue=AV2-352
> [AV2-352] Feature/version check frequency

- package-lock.json
- package.json
- src/app/activity/activity.component.ts
- src/app/activity/activity.service.ts
- src/app/assessment/assessment-routing.module.ts
- src/app/assessment/assessment.component.ts
- src/app/assessment/assessment.module.ts
- src/app/fast-feedback/fast-feedback.service.ts
- src/app/project/project.component.ts
- src/app/project/project.module.ts
- src/app/project/project.service.ts
- src/app/services/shared.service.ts
- src/app/shared/notification/notification.service.ts
- src/app/topic/topic.component.ts
- src/app/topic/topic.module.ts
https://intersective.atlassian.net/browse/AV2-309
> [AV2-309] Feature/progress next activity set

- src/app/services/version-check.service.ts
https://intersective.atlassian.net/browse/AV2-352
> [AV2-352] change interval to 3mins

- src/app/assessment/assessment.component.ts
- src/app/shared/notification/lock-team-assessment-pop-up/lock-team-assessment-pop-up.component.html
- src/app/shared/notification/lock-team-assessment-pop-up/lock-team-assessment-pop-up.component.ts
- src/app/shared/notification/notification.service.ts
> Feature/av2 313/concurrent update on team submission page 

- src/app/achievements/achievements.component.html
- src/app/achievements/achievements.component.ts
- src/app/achievements/achievements.service.ts
1. https://intersective.atlassian.net/browse/AV2-362
1.1 use service methods in html.
> [AV2-362] create variable and method to check achievements have points.

- src/app/achievements/achievements.component.ts
> [AV2-362] update private achievement service to public.

- src/app/switcher/switcher-program/switcher-program.component.html
program switcher typo issue.
Jira story - https://intersective.atlassian.net/browse/AV2-365
> [AV2-365] program switcher typo issue.

- src/app/assessment/assessment.component.html
- src/app/assessment/assessment.component.ts
https://intersective.atlassian.net/browse/AV2-363
> [AV2-363] added continue button for type of assessment

- src/app/assessment/assessment.component.html
- src/app/assessment/assessment.component.ts
- src/app/review-rating/review-rating.component.ts
1) removed “submitted successfully” toast message for marking as read (review popup submission)
2) DONE assessments is still greyed out (for moderated assessment)
> [AV2-363] Feature/task progress bug

- src/app/activity/activity.service.ts
- src/app/assessment/assessment.component.ts
- src/app/auth/auth.service.ts
- src/app/topic/topic.component.ts
warning when user isn't in a team
> [AV2-363] more fixes

- src/app/shared/request/request.service.ts
https://intersective.atlassian.net/browse/AV2-345
> [AV2-345 Bugfix/api error handling

- src/app/shared/request/request.service.ts
https://intersective.atlassian.net/browse/AV2-345
> [AV2-345] api error handling

- src/app/activity/activity.service.ts
- src/app/assessment/assessment.component.ts
- src/app/project/project.component.html
- src/app/project/project.component.ts
- src/app/services/utils.service.ts
- src/app/shared/components/activity-card/activity-card.component.html
- src/app/shared/components/activity-card/activity-card.component.scss
- src/app/topic/topic.component.ts
https://intersective.atlassian.net/browse/AV2-372
> [AV2-372] Feature/sequential activity progress

- src/app/services/storage.service.ts
- src/app/shared/components/description/description.component.html
- src/app/shared/components/description/description.component.ts
- src/app/shared/request/request.service.ts
- src/app/switcher/switcher.service.ts
Jira story - https://intersective.atlassian.net/browse/AV2-374
BE have config in experience to manipulate show more/less descriptions of app.
when BE config true - app need to limit text and show `show more/less` buttons in app descriptions. 
when BE config false - app need to show full description without limit it. and hide `show more/less` buttons.
> Bug/av2 374/update description related to program config

- package-lock.json
- src/app/activity/activity.service.ts
- src/app/shared/components/activity-card/activity-card.component.html
- src/app/shared/components/activity-card/activity-card.component.ts
1. https://intersective.atlassian.net/browse/AV2-311
2. https://intersective.atlassian.net/browse/AV2-380
> [AV2-311] [AV2-380]

- src/app/activity/activity.component.ts
- src/app/assessment/assessment.component.ts
- src/app/services/shared.service.ts
- src/app/tabs/tabs.component.ts
- src/app/topic/topic.component.ts
Issue is videos attach to assessment, topic, or in activity detail or milestone description, continuously paying after leave the page.
Jira story - https://intersective.atlassian.net/browse/AV2-348
> Bug/av2 348/video continues to play after exiting the topic

- src/app/achievements/achievements.component.ts
- src/app/activity/activity.component.ts
- src/app/assessment/assessment.component.ts
- src/app/auth/auth-direct-login/auth-direct-login.component.ts
- src/app/chat/chat-room/chat-room.component.ts
- src/app/events/events.component.ts
- src/app/topic/topic.component.html
- src/app/topic/topic.component.ts
[AV2-380] https://intersective.atlassian.net/browse/AV2-380
This PR was branched out from [master branch](https://github.com/intersective/practera-app-v2/tree/master/), so it's directly mergeable into master (staging).
We, for temporary, shouldn't resolve the conflicts between this PR vs [develop branch](https://github.com/intersective/practera-app-v2/tree/develop/), because that'll also bring in the unfinished new feature/changes code from develop branch.
> [AV2-380] Hotfix/infinite loop (for staging only)

- src/app/chat/chat-room/chat-room.component.html
- src/app/chat/chat-room/chat-room.component.scss
- src/app/chat/chat-room/chat-room.component.ts
- src/app/chat/chat.module.ts
- src/app/shared/directives/autoresize/autoresize.directive.ts
- src/app/shared/shared.module.ts
In this PR fixed issue text box not shrink after send message.
> [AV2-199] Chat enhancement -extend chat message window

- src/app/project/project.component.html
- src/app/project/project.component.scss
In this story need to remove extra space have in milestone page.
need to fix issue in tick icon in activity progress.
Jira - https://intersective.atlassian.net/browse/AV2-382?oldIssueView=true
> [AV2-382] Padding fix on milestone page

- src/app/activity/activity.service.ts
https://intersective.atlassian.net/browse/AV2-430
> [AV2-430] bugfix/process-milestone-with-activity-only

- src/app/project/project.component.html
- src/app/project/project.component.scss
- src/app/shared/components/activity-card/activity-card.component.scss
Need to fixed spacing issue in milestone page and some alignment issues in lock activity.
Jira story - https://intersective.atlassian.net/browse/AV2-426
> [AV2-426] Alignment issues in milestone page when platform changed.

- src/app/project/project.component.html
- src/app/project/project.component.scss
fixed tick icon alignment issue.
> [AV2-426] Alignment issues in milestone page when platform changed

- src/app/project/project.component.html
- src/app/project/project.component.scss
- src/app/shared/components/activity-card/activity-card.component.scss
- src/app/shared/components/description/description.component.scss
there is 3 main issues.
- There is alignment issue on the home page, where there is no padding between 'Current activity' and the activity card.
- There is no padding between milestone name and activity card on the milestone page.
- On the milestone page, there is inconsistent padding between the milestone name and activity card.
JIra story - https://intersective.atlassian.net/browse/AV2-432
> [AV2-432] Alignment issue on the home page

- angular.json
- buildspec-unittest.yml
- src/karma.conf.aws.js
- src/karma.conf.headless.js
implement headless and put it to a code build
> [AV2-406] Feature/headless unit test

- src/app/switcher/switcher-program/switcher-program.component.scss
https://intersective.atlassian.net/browse/AV2-437
> [AV2-437] bugfix/avoid-truncate

- src/app/project/project.component.html
- src/app/project/project.component.scss
- src/app/shared/components/circle-progress/circle-progress.component.html
- src/app/shared/components/circle-progress/circle-progress.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-439?oldIssueView=true
> [AV2-439] Progress circle UI issue in milestone page.

- src/app/auth/auth-registration/auth-registration.component.ts
- src/app/auth/auth-reset-password/auth-reset-password.component.html
- src/app/auth/auth-reset-password/auth-reset-password.component.ts
https://intersective.atlassian.net/browse/AV2-438
> [AV2-438] Bugfix/missing-email-formcontrol

- src/app/activity/activity.component.html
- src/app/activity/activity.component.scss
- src/app/project/project.component.html
- src/app/shared/components/activity-card/activity-card.component.html
- src/app/shared/components/activity-card/activity-card.component.scss
- src/app/shared/notification/lock-team-assessment-pop-up/lock-team-assessment-pop-up.component.html
- src/styles.scss
Jira Story - https://intersective.atlassian.net/browse/AV2-447
> [AV2-447] Activity List / Detail Accessibility Fix

- src/app/chat/chat-list/chat-list.component.html
- src/app/chat/chat-preview/chat-preview.component.html
- src/app/chat/chat-room/chat-room.component.html
- src/app/chat/chat-room/chat-room.component.ts
Jira Story - https://intersective.atlassian.net/browse/AV2-449
> [AV2-449] Chat List / Messages Accessibility fix

- src/app/assessment/assessment.component.ts
JIra Story - https://intersective.atlassian.net/browse/AV2-443
> [AV2-443] Autosave not available - logic changes.

- src/app/assessment/assessment.component.ts
https://intersective.atlassian.net/browse/AV2-443
> [AV2-443] added manual save when go back.

- src/app/assessment/assessment.component.html
https://intersective.atlassian.net/browse/AV2-468
> [AV2-468] re-add for missed button

- src/app/shared/components/clickable-item/clickable-item.component.html
- src/app/shared/components/clickable-item/clickable-item.component.scss
- src/app/shared/components/clickable-item/clickable-item.component.ts
- src/app/switcher/switcher-program/switcher-program.component.html
- src/app/switcher/switcher-program/switcher-program.component.scss
Jira Story - https://intersective.atlassian.net/browse/AV2-458
> [AV2-458] Experience Switcher Enhancement

- src/app/assessment/assessment.component.html
- src/app/questions/oneof/oneof.component.html
- src/app/questions/team-member-selector/team-member-selector.component.html
- src/app/questions/text/text.component.html
- src/app/review-rating/review-rating.component.html
- src/app/reviews/reviews.component.html
Jira story - https://intersective.atlassian.net/browse/AV2-448
> [AV2-448] Assessments and Reviews, Pulse Checks and Review Ratings and Topics

- src/app/assessment/assessment.component.ts
- src/app/events/events.component.html
- src/app/events/events.component.ts
https://intersective.atlassian.net/browse/AV2-489
> [AV2-489] Hotfix/event checking

- src/app/switcher/switcher-program/switcher-program.component.html
- src/app/switcher/switcher-program/switcher-program.component.ts
done missing requirement.
Remove the logout button from switcher page.
> Feature/av2 458/experience switcher enhancement

- src/app/auth/auth-login/auth-login.component.spec.ts
- src/app/auth/auth-login/auth-login.component.ts
- src/app/auth/auth-registration/auth-registration.component.ts
- src/app/switcher/switcher-program/switcher-program.component.ts
- src/app/switcher/switcher.service.spec.ts
- src/app/switcher/switcher.service.ts
Jira story - https://intersective.atlassian.net/browse/AV2-458
added missed registration workflow.
> [AV2-458] Experience Switcher Enhancement - Registration workflow.

- src/app/chat/chat-list/chat-list.component.html
- src/app/chat/chat-list/chat-list.component.scss
- src/app/chat/chat-list/chat-list.component.ts
- src/app/chat/chat-room/chat-room.component.scss
- src/app/chat/chat-room/chat-room.component.ts
- src/app/tabs/tabs.component.scss
Jira story - https://intersective.atlassian.net/browse/AV2-480
> [AV2-480] Desktop view chat - UI Issues

- src/app/settings/settings.component.html
- src/app/settings/settings.component.scss
- src/app/shared/components/contact-number-form/contact-number-form.component.html
- src/app/shared/components/contact-number-form/contact-number-form.component.scss
- src/styles.scss
Please check jira story for UI issue found.
Jira story - https://intersective.atlassian.net/browse/AV2-525
> [AV2-525] ui issues desktop settings page.

- src/app/topic/topic.component.html
- src/styles.scss
Jira story - https://intersective.atlassian.net/browse/AV2-533
> [AV2-533] topic grey text and background

- src/app/overview/project/project.component.html
https://intersective.atlassian.net/browse/AV2-527
> [AV2-527] content hide/show

- src/app/fast-feedback/fast-feedback.component.html
- src/app/fast-feedback/fast-feedback.component.scss
- src/app/shared/components/description/description.component.html
- src/app/shared/components/description/description.component.scss
- src/app/shared/components/description/description.component.ts
- src/app/shared/notification/achievement-pop-up/achievement-pop-up.component.html
- src/app/shared/notification/achievement-pop-up/achievement-pop-up.component.scss
- src/app/shared/notification/achievement-pop-up/achievement-pop-up.component.ts
- src/app/shared/notification/lock-team-assessment-pop-up/lock-team-assessment-pop-up.component.html
- src/app/shared/notification/lock-team-assessment-pop-up/lock-team-assessment-pop-up.component.scss
- src/app/shared/notification/lock-team-assessment-pop-up/lock-team-assessment-pop-up.component.ts
- src/app/shared/notification/notification.service.ts
- src/styles.scss
popup size issues found in achievement popup and lock assessment popup.
and font sizes, button sizes, alignment issues also there in popups.
check jira story comment for fixes.
Jira story - https://intersective.atlassian.net/browse/AV2-534
> [AV2-534] modal window issues desktop view

- package-lock.json
- package.json
- src/app/overview/home/slidable/slidable.component.ts
https://intersective.atlassian.net/browse/AV2-547
> [AV2-547] moment to compare dates

- src/app/topic/topic.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-499
> [AV2-499] Error message on topic mark as read prompt

- src/app/assessment/assessment.component.spec.ts
- src/app/assessment/assessment.component.ts
- src/app/services/utils.service.ts
https://intersective.atlassian.net/browse/AV2-535
> [AV2-535] Bugfix/submiter-reviewer-compulsory-question

- src/app/services/shared.service.ts
JIra story - https://intersective.atlassian.net/browse/AV2-556
> [AV2-556] topic video start playing after navigate to dashboard

- package-lock.json
- src/app/questions/file/file-display/file-display.component.ts
- src/app/shared/filestack/filestack.component.ts
- src/app/shared/filestack/filestack.service.ts
- removed unnecessary console.log code
> [AV2-369] fixed minor glitches

- src/app/activity/activity.service.ts
Jira story - https://intersective.atlassian.net/browse/AV2-536
> [AV2-536] a participant is able to progress to a team assessment if not in a team

- src/app/shared/components/description/description.component.html
- src/app/shared/components/description/description.component.scss
Jira story - https://intersective.atlassian.net/browse/AV2-557
> [AV2-557] show more/less does not look to be clickable

- src/app/auth/auth-direct-login/auth-direct-login.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-505?oldIssueView=true
> [AV2-505] redirect user to registration page from direct link

- package-lock.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/device-info/device-info.component.html
- src/app/device-info/device-info.component.ts
https://intersective.atlassian.net/browse/AV2-574
> [AV2-574] harvest device info

- src/app/device-info/device-info.component.ts
https://intersective.atlassian.net/browse/AV2-574
> [AV2-574] fixed lint error

- src/app/device-info/device-info.component.html
- src/app/services/utils.service.ts
https://intersective.atlassian.net/browse/AV2-574
> [AV2-574] highest priority given to tablet (desktop mode)

- src/app/assessment/assessment.component.html
https://intersective.atlassian.net/browse/AV2-583
> [AV2-583] bugfix/unseeable-text

- src/app/assessment/assessment.component.ts
- src/app/topic/topic.component.ts
https://intersective.atlassian.net/browse/AV2-573
> [AV2-573] bugfix/text-removed

- src/app/overview/home/home.component.html
- src/app/overview/home/home.component.scss
- src/app/overview/project/project.component.html
Jira story - https://intersective.atlassian.net/browse/AV2-580?oldIssueView=true
> [AV2-580] Desktop View and mobile - Dashboard UI Issues

- src/app/topic/topic.service.ts
Jira story - https://intersective.atlassian.net/browse/AV2-584
> [AV2-584] Desktop -topics with no text content still have blank white box

- src/app/achievements/achievements.component.html
- src/app/achievements/achievements.component.scss
- src/app/achievements/achievements.component.spec.ts
- src/app/achievements/achievements.component.ts
- src/app/overview/home/home.component.html
- src/app/shared/components/achievement-badge/achievement-badge.component.html
- src/app/shared/components/achievement-badge/achievement-badge.component.scss
- src/app/shared/components/achievement-badge/achievement-badge.component.ts
Jira Story - https://intersective.atlassian.net/browse/AV2-570
check Jira story for update information and UI update screenshots.
> [Av2-570] Desktop View - achievements page

- e2e/protractor-base.conf.js
- e2e/protractor-ci.conf.js
- e2e/protractor-dev.default.conf.js
- e2e/protractor.conf.js
others configuration files should inherit the base configuration.
> provide a base protractor base configuration file

- src/app/questions/file/file.component.spec.ts
- src/app/shared/filestack/filestack.component.spec.ts
- src/app/shared/filestack/filestack.component.ts
- src/app/shared/filestack/filestack.service.spec.ts
- src/app/shared/filestack/filestack.service.ts
- src/test.ts
https://intersective.atlassian.net/browse/AV2-598
> [AV2-598] Feature/filestack-unit-test

- src/app/questions/text/text.component.html
- src/app/questions/text/text.component.ts
@chaw this should fix the iE text reversal problem. Please test and deploy ASAP.
> hotfix for IE/Edge text reversal on Windows

- src/app/questions/file/file-display/file-display.component.spec.ts
- src/app/questions/file/file-display/file-display.component.ts
- src/test.ts
https://intersective.atlassian.net/browse/AV2-612
> [AV2-612] Feature/file display unit test

- src/app/settings/settings.component.html
- src/app/settings/settings.component.scss
- src/app/switcher/switcher-program/switcher-program.component.html
- src/app/switcher/switcher.service.spec.ts
- src/app/switcher/switcher.service.ts
- src/styles.scss
Jira story - https://intersective.atlassian.net/browse/AV2-611
> [AV2-611] auto resize switcher image using filestack url parameters

- src/app/settings/settings.component.spec.ts
- src/app/settings/settings.component.ts
Jira - https://intersective.atlassian.net/browse/AV2-611
**In this PR fixed issue,**
a new participant enrolls into a new program, the URL in the settings page does not resize with parameters.
> Feature/av2 611/auto resize switcher image using filestack url parameters

- src/app/chat/chat-room/chat-room.component.html
- src/app/go-mobile/go-mobile.component.html
- src/app/go-mobile/go-mobile.component.spec.ts
- src/app/go-mobile/go-mobile.component.ts
- src/app/go-mobile/go-mobile.module.ts
- src/app/questions/file/file-display/file-display.component.ts
- src/app/shared/components/contact-number-form/contact-number-form.component.html
- src/app/shared/components/contact-number-form/contact-number-form.component.spec.ts
- src/app/shared/components/contact-number-form/contact-number-form.component.ts
- src/test.ts
- src/testing/mocked.service.ts
https://intersective.atlassian.net/browse/AV2-409
> [AV2-409] Task/go mobile unit test

- src/app/achievements/achievements.component.html
- src/app/activity/activity.component.html
- src/app/assessment/assessment.component.html
- src/app/event-list/event-list.component.html
- src/app/overview/home/home.component.html
- src/app/shared/components/list-item/list-item.component.html
- src/app/shared/components/list-item/list-item.component.scss
- src/app/topic/topic.component.html
- src/theme/pfas/_colors.scss
- src/theme/pfas/_ionic-components.scss
Jira - https://intersective.atlassian.net/browse/AV2-601
In this story only fixing font colors. not font sizes.
> [AV2-601] WCAG color requirements

- src/app/overview/overview.component.scss
- src/app/shared/directives/float/float.directive.ts
Jira - https://intersective.atlassian.net/browse/AV2-616
> [AV2-616] Unexpected yellow frame shows when scrolling down the notifications on desktop view

- src/app/topic/topic.component.ts
Jira - https://intersective.atlassian.net/browse/AV2-603
> [AV2-603] topic back button confirmation button display red messages

- src/app/overview/project/project.component.html
- src/app/overview/project/project.component.scss
Jira - https://intersective.atlassian.net/browse/AV2-621
> [AV2-621] fixed padding issue in milestone section on home page.

- src/app/shared/components/description/description.component.ts
Jira - https://intersective.atlassian.net/browse/AV2-602
> [AV2-602] show more/less does not act with the configuration

- src/app/chat/chat.service.spec.ts
Jira - https://intersective.atlassian.net/browse/AV2-401
> Feature/av2 401/unit test for chat service

- src/app/chat/chat-room/chat-room.component.html
- src/app/chat/chat-room/chat-room.component.scss
- src/app/chat/chat-room/chat-room.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-299
> Feature/av2 299/mov video files are not being transcoded

- package-lock.json
- package.json
- src/app/topic/topic.component.html
- src/app/topic/topic.component.scss
- src/app/topic/topic.component.ts
- src/app/topic/topic.service.ts
- src/global.scss
- src/styles.scss
Jira story - https://intersective.atlassian.net/browse/AV2-597
> Feature/av2 597/change the way we display practera videos

- src/app/topic/topic.component.ts
Jira - https://intersective.atlassian.net/browse/AV2-597
**Please check jira story last comment that have video. and i have explain the reason for adding new code changes.**
> [AV2-597] Change the way we display Practera videos

- src/app/services/utils.service.ts
Jira story - https://intersective.atlassian.net/browse/AV2-641
In this changes haven't done any update to UI or how we show dates in app. formats remain as same as before. changes done to logic how we detect tomorrow or yesterday.
> Feature/av2 641/change the way we detect tomorrow or yesterday

- src/app/topic/topic.component.ts
- src/styles.scss
Jira story - https://intersective.atlassian.net/browse/AV2-677
> Hotfix/av2 677/video can not click to play when we go to the topic with continue button

- src/app/topic/topic.component.html
- src/app/topic/topic.component.ts
- src/app/topic/topic.service.ts
In this PR fixed issue happens when navigate to topic from continue button.
JIRA story - https://intersective.atlassian.net/browse/AV2-677
> [AV2-677] video can not click to play when we go to the topic with continue button

- src/app/go-mobile/go-mobile.component.ts
- src/app/shared/components/contact-number-form/contact-number-form.component.ts
allowing 9 or 10 digits for NZ
> Master to Develop

- src/app/overview/home/home.component.html
- src/app/overview/home/home.component.scss
- src/app/overview/home/home.component.ts
- src/app/overview/overview.component.html
- src/app/overview/overview.component.scss
- src/app/overview/project/project.component.html
- src/app/overview/project/project.component.scss
- src/app/shared/components/achievement-badge/achievement-badge.component.html
- src/app/shared/components/achievement-badge/achievement-badge.component.scss
Jira story - https://intersective.atlassian.net/browse/AV2-661
> Feature/av2 661/program switcher image on dashboard

- src/app/event-detail/event-detail.component.html
- src/app/shared/components/list-item/list-item.component.html
capitalize the zoom text in events details and in list item.
> [hotfix] Zoom Typo Issue

- src/app/topic/topic.component.spec.ts
- src/app/topic/topic.component.ts
- src/app/topic/topic.service.spec.ts
- src/app/topic/topic.service.ts
Jira story - https://intersective.atlassian.net/browse/AV2-696
> Feature/av2 696/log start and stop reading of a topic

- src/app/overview/home/home.component.html
- src/app/overview/home/home.component.scss
Jira story - https://intersective.atlassian.net/browse/AV2-707
changes done
- added 24px margin to bottom of project image and progress circle section.
- added round corners and shadow, that we use in switcher page to image.
> [AV2-707] Project lead image styling issue

- src/app/assessment/assessment.component.html
- src/app/assessment/assessment.component.scss
- src/app/questions/file/file.component.html
- src/app/questions/file/file.component.scss
- src/app/questions/file/file.component.ts
- src/app/questions/multiple/multiple.component.html
- src/app/questions/multiple/multiple.component.scss
- src/app/questions/multiple/multiple.component.spec.ts
- src/app/questions/multiple/multiple.component.ts
- src/app/questions/oneof/oneof.component.html
- src/app/questions/oneof/oneof.component.scss
- src/app/questions/oneof/oneof.component.spec.ts
- src/app/questions/oneof/oneof.component.ts
- src/app/questions/team-member-selector/team-member-selector.component.html
- src/app/questions/team-member-selector/team-member-selector.component.scss
- src/app/questions/team-member-selector/team-member-selector.component.spec.ts
- src/app/questions/team-member-selector/team-member-selector.component.ts
- src/app/questions/text/text.component.html
- src/app/questions/text/text.component.scss
- src/app/questions/text/text.component.spec.ts
- src/app/questions/text/text.component.ts
- src/app/shared/filestack/filestack.component.scss
- src/styles.scss
- src/theme/variables.scss
Jira story - https://intersective.atlassian.net/browse/AV2-630
There are lots of UI changes and also some changes done to the code so please check Jira Story details and Comments.
> Feature/av2 630/confusion while reviewing student answers

- .gitignore
- angular.json
- ios/App/App.xcodeproj/project.pbxproj
- ios/App/App/App.entitlements
- src/well-known/apple-app-site-association
- src/well-known/assetlinks.json.custom
https://intersective.atlassian.net/browse/AV2-648
> [AV2-648] Feature/deep-linking

- src/app/chat/chat-list/chat-list.component.html
- src/app/chat/chat-room/chat-room.component.html
- src/app/chat/chat-room/chat-room.component.scss
- src/app/chat/chat.service.ts
Jira story - https://intersective.atlassian.net/browse/AV2-733
> [AV2-733] Update chat room UI styles

- src/app/chat/chat-list/chat-list.component.scss
- src/app/chat/chat-list/chat-list.component.ts
- src/app/chat/chat-room/chat-room.component.scss
- src/app/chat/chat-room/chat-room.component.ts
- src/app/overview/home/home.service.spec.ts
- src/app/overview/home/home.service.ts
- src/app/shared/pusher/pusher.service.ts
- src/app/tabs/tabs.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-724
Fixed issues.
- added message id to get from pusher data.
- fixed attachment not showing issue.
- fixed todo item notification for chat issues.
- fixed pusher channel unsubscribe issue.
- change message bubble styles.
- change send attachment styles.
- fixed avatar style.
> Feature/av2 724/chat   increment 1

- src/app/chat/chat-room/chat-room.component.html
- src/app/chat/chat-room/chat-room.component.scss
- src/app/chat/chat-room/chat-room.component.ts
- src/app/overview/home/home.component.spec.ts
- src/app/overview/home/home.component.ts
- src/app/tabs/tabs.component.spec.ts
- src/app/tabs/tabs.component.ts
update event name chat to chat:new-message to update dashboard notification card and count in tab
Fixed mobile view issue.
> [AV2-724] Chat - Increment 1 (1)

- src/app/app.component.html
- src/app/app.component.ts
- src/styles.scss
Jira story - https://intersective.atlassian.net/browse/AV2-742.
for Study perth we need to add header and footer outside of out component. so i put in in app component.
and also that header and footer html content need to get from experience config. and it need to how after login.
and another condition is in mobile view we are not showing footer.
to get space for header and footer need give space to our router outlet. add some styles and load them by checking those conditions.
> Feature/av2 742/allow custom html header and footer in the app

- src/app/app.component.html
- src/styles.scss
added some styles to custom html content.
> [AV2-742] allow a custom html header and footer in the app

- buildspec.yml
- src/app/app.component.html
- src/app/app.component.ts
- src/app/chat/chat-room/chat-room.component.ts
- src/styles.scss
This branch create to resolved the conflicts found on merging develop to master.
this branch take out from develop, and merge master to this. and conflicts are resolved. so need merge back to develop.
> Av2 724/develop

- buildspec-unittest.yml
> change the datetime part of the test report

- src/app/auth/auth-direct-login/auth-direct-login.component.spec.ts
- src/app/auth/auth-direct-login/auth-direct-login.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-741
check jira story comment for video.
> [AV2-741] added time out untill finish some background process.

- src/app/chat/chat-room/chat-room.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-751
> [AV2-751] hotfix - Chat messages duplicating when loading previous messages.

- src/app/assessment/assessment.service.ts
- src/app/questions/multiple/multiple.component.html
- src/app/questions/multiple/multiple.component.scss
- src/app/questions/multiple/multiple.component.ts
- src/app/questions/oneof/oneof.component.html
- src/app/questions/oneof/oneof.component.scss
- src/app/questions/oneof/oneof.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-728
check comments to see UI updates.
**Note**
Added new logic to show explanation after clicks on submit button. previously explanation can only see if user return back to assessment. with new changes, user can see explanation of the answers before they clicks on continue button.
> Feature/av2 728/quiz answer explanation field issue

- src/app/auth/auth-direct-login/auth-direct-login.component.ts
- src/app/auth/auth-registration/auth-registration.component.html
- src/app/auth/auth-registration/auth-registration.component.scss
- src/app/auth/auth-registration/auth-registration.component.ts
- src/app/auth/auth.module.ts
- src/app/auth/terms-conditions-preview/terms-conditions-preview.component.html
- src/app/auth/terms-conditions-preview/terms-conditions-preview.component.scss
- src/app/auth/terms-conditions-preview/terms-conditions-preview.component.spec.ts
- src/app/auth/terms-conditions-preview/terms-conditions-preview.component.ts
- src/styles.scss
Jira story - https://intersective.atlassian.net/browse/AV2-738
> Feature/av2 738/direct link add terms condition page

- src/app/chat/chat-room/chat-room.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-759
> [AV2-759] chat direct link does not show chat messages

- src/app/chat/chat-room/chat-room.component.html
- src/app/chat/chat-room/chat-room.component.ts
Jira story - https://intersective.atlassian.net/browse/AV2-758.
> [AV2-758] chat encounters error on file messages not having mimetype.

- .github/workflows/codeql-analysis.yml
- src/karma.conf.aws.js
apply unit tests thresholds
apply github code analysis
> apply coverage thresholds

- README.md
- docs/components/chatListComponent.md
- docs/docs.md
- docs/services/chatService.md
- src/app/app.module.ts
- src/app/chat/chat-list/chat-list.component.html
- src/app/chat/chat-list/chat-list.component.spec.ts
- src/app/chat/chat-list/chat-list.component.ts
- src/app/chat/chat-room/chat-room.component.html
- src/app/chat/chat-room/chat-room.component.scss
- src/app/chat/chat-room/chat-room.component.spec.ts
- src/app/chat/chat-room/chat-room.component.ts
- src/app/chat/chat.service.spec.ts
- src/app/chat/chat.service.ts
- src/app/overview/home/home.service.spec.ts
- src/app/overview/home/home.service.ts
- src/app/shared/pusher/pusher.service.spec.ts
- src/app/shared/pusher/pusher.service.ts
- src/app/shared/request/request.service.spec.ts
- src/app/shared/request/request.service.ts
- src/app/tabs/tabs.service.spec.ts
- src/app/tabs/tabs.service.ts
- src/environments/environment.ts
- src/karma.conf.js
Jira story - https://intersective.atlassian.net/browse/AV2-766
> Feature/av2 766/update chat api calls to new graphql apis

- src/app/chat/chat-room/chat-room.component.spec.ts
- src/app/chat/chat-room/chat-room.component.ts
- src/app/chat/chat.service.spec.ts
- src/app/chat/chat.service.ts
Update App chat components to new API change.
Jira story - https://intersective.atlassian.net/browse/AV2-766
> [AV2-766] Update chat API calls to new GraphQL APIs.

- src/app/chat/chat-info/chat-info.component.html
- src/app/chat/chat-info/chat-info.component.scss
- src/app/chat/chat-info/chat-info.component.spec.ts
- src/app/chat/chat-info/chat-info.component.ts
- src/app/chat/chat-room/chat-room.component.html
- src/app/chat/chat-room/chat-room.component.scss
- src/app/chat/chat-room/chat-room.component.spec.ts
- src/app/chat/chat-room/chat-room.component.ts
- src/app/chat/chat-view/chat-view.component.html
- src/app/chat/chat-view/chat-view.component.scss
- src/app/chat/chat-view/chat-view.component.spec.ts
- src/app/chat/chat-view/chat-view.component.ts
- src/app/chat/chat.module.ts
- src/styles.scss
Jira story - https://intersective.atlassian.net/browse/AV2-749
This PR have changes related to adding info page to chat. Please check jira story comments for videos.
> Feature/av2 749/add chat info page

- src/app/services/push-notification.service.spec.ts
- src/app/services/push-notification.service.ts
https://intersective.atlassian.net/browse/AV2-793
> [AV2-793] fixed pnservice test

- src/app/services/push-notification.service.spec.ts
- src/app/services/push-notification.service.ts
https://intersective.atlassian.net/browse/AV2-793
> [AV2-793 Task/pn-unitest

- src/app/overview/home/home.service.spec.ts
- src/app/overview/home/home.service.ts
current activity is no longer displaying at the home screen. The relevant logics do not have to be there and also the logics are not capable to deal with the situation that there is no on-going activity and no activity under the last milestone. This could also happen if a program is purely for a participant and no mentor activity.
> remove currentActivityId related logics and functions

- .github/actions/unit-tests-build/action.yml
- .github/workflows/main.yml
- CODEOWNERS
move unit test from aws codebuild to github actions
> move unit test from aws codebuild to github actions

- src/app/switcher/switcher.service.spec.ts
- src/app/switcher/switcher.service.ts
- src/testing/fixtures/programs.ts
1. ensure access experience config only if it exists
2. add an additional test for this case
> ensure access experience config only if it exists

- .github/actions/unit-tests-build/action.yml
- .github/workflows/main.yml
- CODEOWNERS
- src/app/overview/home/home.service.spec.ts
- src/app/overview/home/home.service.ts
- src/app/overview/overview.component.spec.ts
- src/app/switcher/switcher.service.spec.ts
- src/app/switcher/switcher.service.ts
- src/app/tabs/tabs.component.spec.ts
- src/app/tabs/tabs.component.ts
- src/testing/fixtures/programs.ts
https://intersective.atlassian.net/browse/AV2-824
**Checklist:**
- [ x ] Unit test completed?: (Y)
- [  ] Docs folder up to date?: (Y/N)
- [  ] Add if anything missed: (N)
> Update native AppV2 with V2.6.6.8

- src/app/switcher/switcher.service.spec.ts
- src/testing/fixtures/programs.ts
a test for null experience
**Checklist:**
- [ x ] Unit test completed?: Y
- [ x ] Docs folder up to date?: Y
> tests for null experience

- .github/workflows/lint_unitest-develop.yml
- .github/workflows/lint_unitest-feature.yml
- .github/workflows/lint_unitest-master.yml
- src/karma.conf.sonarci.js
1. use ubuntu ChromeHeadless instead
2. use repo local angular cli directly
**Checklist:**
- [ x ] Unit test completed?: Y
- [ x ] Docs folder up to date?: Y
- [ x ] Add if anything missed: N
> use ubuntu ChromeHeadless instead

- angular.json
- buildspec.yml
update well known folders path to be a dot folder
**Checklist:**
- [ x ] Unit test completed?: Y
- [ x ] Docs folder up to date?: Y
> update well known folders path

- src/app/auth/unauthorized.guard.ts
- src/environments/environment.custom.ts
- src/environments/environment.local.ts
- src/environments/environment.sandbox.ts
https://intersective.atlassian.net/browse/AV2-825
`Add here`
**Checklist:**
> [AV2-825]redirect to login service for not logged in user

- src/app/app.component.ts
- src/app/auth/auth-global-login/auth-global-login.component.html
- src/app/auth/auth-global-login/auth-global-login.component.spec.ts
- src/app/auth/auth-global-login/auth-global-login.component.ts
- src/app/auth/auth-routing.module.ts
- src/app/auth/auth.module.ts
- src/app/auth/auth.service.spec.ts
- src/app/auth/auth.service.ts
- src/app/auth/unauthorized.guard.ts
- src/environments/environment.custom.ts
- src/environments/environment.local.ts
- src/environments/environment.sandbox.ts
- src/environments/environment.trial.ts
- src/environments/environment.us.ts
> [AV2-827]appv2 endpoint where we login a user from a jwt token

- src/app/settings/settings.component.html
https://intersective.atlassian.net/browse/AV2-812
`Add here`
**Checklist:**
> Remove goToApp button

- README.md
- src/app/activity/activity.component.spec.ts
- src/app/activity/activity.component.ts
- src/app/activity/activity.service.spec.ts
- src/app/activity/activity.service.ts
- src/app/app-routing.module.ts
- src/app/auth/auth-direct-login/auth-direct-login.component.spec.ts
- src/app/auth/auth-direct-login/auth-direct-login.component.ts
- src/app/services/router-enter.service.ts
- src/app/services/storage.service.spec.ts
- src/app/services/storage.service.ts
- src/app/services/utils.service.ts
- src/app/settings/settings.component.spec.ts
- src/app/settings/settings.component.ts
- src/app/tasks/tasks.component.ts
> [AV2-818]handle lti return url on activity detail page

- android/.idea/misc.xml
- src/app/shared/components/pn-permission-modal/pn-permission-modal.component.html
- src/app/shared/components/pn-permission-modal/pn-permission-modal.component.ts
https://intersective.atlassian.net/browse/AV2-829
`Add here`
**Checklist:**
> Task/av2 829/yes button functionality native app

- README.md
- src/app/activity/activity.component.spec.ts
- src/app/activity/activity.component.ts
- src/app/activity/activity.service.spec.ts
- src/app/activity/activity.service.ts
- src/app/app-routing.module.ts
- src/app/auth/auth-direct-login/auth-direct-login.component.spec.ts
- src/app/auth/auth-direct-login/auth-direct-login.component.ts
- src/app/services/router-enter.service.ts
- src/app/services/storage.service.spec.ts
- src/app/services/storage.service.ts
- src/app/services/utils.service.ts
- src/app/settings/settings.component.spec.ts
- src/app/settings/settings.component.ts
- src/app/tasks/tasks.component.ts
> [AV2-818]to master branch

- src/app/auth/unauthorized.guard.ts
https://intersective.atlassian.net/browse/AV2-836
add logic not to navigate to global login if it registration.
**Checklist:**
- [ x ] Unit test completed?: (Y)
- [ x ] Docs folder up to date?: (Y)
> [AV2-836] Appv2 - global login bugs.

- android/.idea/misc.xml
- src/app/shared/components/pn-permission-modal/pn-permission-modal.component.html
- src/app/shared/components/pn-permission-modal/pn-permission-modal.component.scss
- src/styles.scss
https://intersective.atlassian.net/browse/AV2-838
https://intersective.atlassian.net/browse/AV2-837
`Add here`
**Checklist:**
> Permission modal layout

- ios/App/Podfile
- src/styles.scss
https://intersective.atlassian.net/browse/AV2-839
`Add here`
**Checklist:**
> update modal wrapper css

- src/app/assessment/assessment.component.html
- src/app/assessment/assessment.component.spec.ts
- src/app/assessment/assessment.component.ts
https://intersective.atlassian.net/browse/AV2-768
- added 'pending review' to footer text in assessment page.
- added extra logic 'Reviewed by' to not to show in pending state.
- update the unit test.
**Checklist:**
- [ x ] Unit test completed?: (Y)
> Bug/av2 768/assessment review returns wrong statement

- src/app/assessment/assessment.component.html
- src/app/assessment/assessment.component.spec.ts
- src/app/assessment/assessment.component.ts
https://intersective.atlassian.net/browse/AV2-768
- update assessment page to show pending review.
- added new unit test for new changes.
- added changes to show reviewed by after review publish.
**Checklist:**
- [ x ] Unit test completed?: (Y)
> [AV2-768] Assessment review returns wrong statement "reviewed by"

- .github/workflows/release-au.yml
- .github/workflows/release-lf.yml
- .github/workflows/release-nu.yml
- .github/workflows/release-p1-stage.yml
- .github/workflows/release-p2.yml
- .github/workflows/release-uk.yml
- .github/workflows/release-us.yml
- .github/workflows/sandbox.yaml
- .github/workflows/stage.yml
`removed cat command for security reason`
**Checklist:**
> remove cat command

- .github/workflows/release-p2.yml
- .github/workflows/sandbox.yaml
- .github/workflows/stage.yml
`Minor fix to p2 release`
**Checklist:**
All Checklists are okay.
> p2-api-fix
